# Generated by Django 4.2.16 on 2025-01-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_produto_img_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='qtde',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='home.ItemPedido', to='home.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Novo'), (2, 'Em andamento'), (3, 'Concluido'), (4, 'Cancelado')], default=1),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produto'),
        ),
    ]
