# Generated by Django 4.2.16 on 2025-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_itempedido_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
