# Generated by Django 4.2.16 on 2025-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pedido_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ativo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
